cricketproject-master/cricketapp/urls.py
from django.urls import path
from django.conf.urls import url
from .views import TeamList,TeamInformationView,PointsTableView,MatchDetailsView,ScheduleMatch

app_name = 'cricketapp'

urlpatterns = [
    path('', TeamList.as_view(), name='team-list'),
    path('team-list/', TeamList.as_view(), name='team-list'),
    path('teaminfo/<int:team_id>/', TeamInformationView.as_view(), name="teaminfo"),
    path('pointstable/', PointsTableView.as_view(), name='pointstable'),
    path('matchdetails/', MatchDetailsView.as_view(), name='matchdetails'),
    path('schedule-match/', ScheduleMatch.as_view(), name='schedule-match'),
]

cricketproject-master/cricketproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cricketapp.urls')),
    path('cricketapi/', include('cricketapp.urls'))
]

cricketproject-master/cricketapp/models.py
# Create your models here.
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import signals
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _




class Team(models.Model):
   #Team model contain details of cricket team

    name = models.CharField(null=False,blank=False,max_length=100)
    logouri = models.URLField(_('Logo'), blank=False,
                            null=False, max_length=4096)
    club_state = models.CharField(null=False,blank=False,max_length=100)
    created_date = models.DateTimeField(_("Created date"), auto_now_add=True)
    updated_date = models.DateTimeField(_("Updated date"), auto_now=True)


    def __str__(self):
        return self.name


class Players(models.Model):
    ''' Players model contain information of cricket players'''

    first_name = models.CharField(null=False,blank=False,max_length=100)
    last_name = models.CharField(null=True,blank=True,max_length=100)
    image_uri = models.URLField(_('Player Picture'),blank=True,
                              null=True, max_length=4096)
    jersey_number = models.PositiveIntegerField(unique=True,blank=False,null=False)
    country = models.CharField(null=False,blank=False,max_length=100)
    team = models.ForeignKey(Team, db_index=True, blank=True, null=True, related_name="team_players",verbose_name=_('Team'),on_delete=models.PROTECT)
    created_date = models.DateTimeField(_("Created date"), auto_now_add=True)
    updated_date = models.DateTimeField(_("Updated date"), auto_now=True)

    def __str__(self):
        return self.first_name


class PlayerHistory(models.Model):
    ''' PlayerHistory model contain details information of players cricket career'''

    player = models.ForeignKey(Players, db_index=True, blank=False, null=False, related_name="player",
                                verbose_name=_('Players'),on_delete=models.PROTECT)
    matches = models.PositiveIntegerField(blank=True,null=True)
    runs = models.PositiveIntegerField(_("Runs"),blank=True,null=True)
    wickets = models.PositiveIntegerField(_("Wickets"),blank=True,null=True)
    centuries = models.PositiveIntegerField(_("Centuries"),blank=True,null=True)
    fifties = models.PositiveIntegerField(_("Fifties"),blank=True,null=True)
    high_score = models.PositiveIntegerField(_("High Score"),blank=True,null=True)
    created_at = models.DateTimeField(_("created_at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated_at"), auto_now=True)


class Match(models.Model):
    ''' Match model contain match details '''
    playing_team1 = models.ForeignKey(Team, db_index=True, blank=False, null=False, related_name="playing_playing_playing_team1",on_delete=models.PROTECT)
    playing_team2 = models.ForeignKey(Team, db_index=True, blank=False, null=False, related_name="playing_playing_playing_team2",on_delete=models.PROTECT)
    winner = models.ForeignKey(Team, db_index=True, blank=True, null=True, related_name="winner",on_delete=models.PROTECT)
    created_at = models.DateTimeField(_("created_at"), auto_now_add=True)
    updated_at= models.DateTimeField(_("updated_at"), auto_now=True)

    def save(self, *args, **kwargs):
        if self.playing_team1 is not None and (self.winner == self.playing_team2 or self.winner == self.playing_team2):
            super().save(*args, **kwargs)
        elif self.winner is None:
            super().save(*args, **kwargs)
        else:
            raise ValidationError(u'Please enter a valid team')


class PointsTable(models.Model):
    ''' PointsTable model contain points collected by cricket teams '''

    team = models.OneToOneField(Team, max_length=50, related_name='team_points',on_delete=models.PROTECT)
    points = models.PositiveIntegerField(default=0)


def save_points(sender, instance, created,update_fields, **kwargs):
    if not created:
        team = get_object_or_404(PointsTable, team=instance.winner)
        team.points +=2
        team.save()

"""Signal to save points of the winning team"""

signals.post_save.connect(receiver=save_points, sender=Match)

cricketproject-master/cricketapp/views.py
from django.shortcuts import render
from .models import Team,Players,PointsTable,Match
from django.views.generic import TemplateView, ListView
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status

# Create your views here.

#template view code start here
class TeamList(ListView):
    context_object_name = 'allteam'
    template_name = 'teamlist.html'
    model = Team


class TeamInformationView(ListView):
    template_name = 'team_info.html'
    model = Players

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        players = context['object_list'].filter(team=self.kwargs['team_id'])
        context['teamdata'] = players
        context['team_name'] = players[0].team.name
        return context
     

class PointsTableView(ListView):
    template_name = 'pointstable.html'
    context_object_name = 'points'
    model = PointsTable


class MatchDetailsView(ListView):
    template_name = 'matchdetails.html'
    context_object_name = 'allmatch'
    model = Match

#template view code end here 
# =======================================================

#schedule match api code started
class ScheduleMatch(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self,request):
        try:
            matchscheduler()
            return Response({"success": True, "message": 'MatchScheduled'}, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({"is_success": False, "message": 'Not Scheduled'}, status=status.HTTP_400_BAD_REQUEST)


def matchscheduler():
	randamteam = Team.objects.order_by('?')[:2]
	if randamteam:
	    Match.objects.create(playing_team1=randamteam[0],playing_team2=randamteam[1],winner=None)

#schedule match api code started

cricketproject-master/templates/matchdetails.html
{% load i18n %}
{% block title %}
    {% trans "Game Fixture" %}
{% endblock %}
<style>
table, td, th {  
  border: 1px solid #ddd;
  text-align: left;
}

table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 15px;
}
</style>
{% block content %}

    {% if allmatch %}
        <table>    
            <thead>
                <tr>
                    <th>{% trans " TeamA" %}</th>
                    <th>{% trans "TeamB" %}</th>
                    <th>{% trans "Winning Team" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for match in allmatch %}
                    <tr>
                        <td><a href="{% url 'cricketapp:teaminfo' match.playing_team1.id %}" >{{ match.playing_team1.name|default:"-" }}</a></td>
                        <td><a href="{% url 'cricketapp:teaminfo' match.playing_team2.id %}" >{{ match.playing_team2.name|default:"-" }}</a></td>
                        <td>{{ match.winner.name|default:"-" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>{% trans "No data found" %}</p>
    {% endif %}
{% endblock content %}

cricketproject-master/templates/pointstable.html
{% load i18n %}
{% block title %}
    {% trans "Points Table" %}
{% endblock %}
<style>
table, td, th {  
  border: 1px solid #ddd;
  text-align: left;
}

table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 15px;
}
</style>
{% block content %}

    {% if points %}
        <table>
            <thead>
                <tr>
                    <th>{% trans "Team Name" %}</th>
                    <th>{% trans "Points" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for point in points %}
                    <tr>
                        <td><a 
                            href="{% url 'cricketapp:teaminfo' point.team.id %}">{{ point.team.name|default:"-" }}</a></td>
                        <td>{{ point.points|default:"-" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>{% trans "no data found" %}</p>
    {% endif %}
{% endblock content %}

cricketproject-master/templates/team_info.html
{% load i18n %}
{% block title %}
{% trans "Players List" %}
<p>TEAMNAME:{{team_name}}</p> 
{% endblock %}
<style>
table, td, th {  
  border: 1px solid #ddd;
  text-align: left;
}

table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 15px;
}
</style>
{% block content %}

    {% if teamdata %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{% trans "Name" %}</th>
                    <th>{% trans "Player  Picture" %}</th>
                    <th>{% trans "Jersey Number" %}</th>
                    <th>{% trans "Country" %}</th>
                    <th>{% trans "Matches Played" %}</th>
                    <th>{% trans "Wickets" %}</th>
                    <th>{% trans "Runs" %}</th>
                    <th>{% trans "Centuries" %}</th>
                    <th>{% trans "Fifties" %}</th>
                    <th>{% trans "Highest Score" %}</th>
                    <th>{% trans "Team" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for data in teamdata %}
                    <tr>
                        <td>{{ data.first_name|default:"-" }}</td>
                        <td> <p><img src="{{ data.image_uri }}" width="80px"></p> </td>
                        <td>{{ data.jersey_number|default:"-" }}</td>
                        <td>{{ data.country|default:"-" }}</td>
                        <td>{% for a in data.player.all %}
                                {{a.matches}}
                                {% empty %}
                             {% endfor %}</td>
                        <td>{% for b in data.player.all %}
                                {{b.wickets}}
                                {% empty %}
                             {% endfor %}</td>
                        <td>{% for c in data.player.all %}
                                {{c.runs}}
                                {% empty %}
                             {% endfor %}</td>
                        <td>{% for d in data.player.all %}
                                {{d.centuries}}
                                {% empty %}
                             {% endfor %}</td>
                        <td>{% for e in data.player.all %}
                                {{e.fifties}}
                                {% empty %}
                             {% endfor %}</td>
                        <td>{% for f in data.player.all %}
                                {{f.high_score}}
                                {% empty %}
                             {% endfor %}</td>
                        <td>{{ data.team.name|default:"-" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>{% trans "No Player found" %}</p>
    {% endif %}
{% endblock content %}

cricketproject-master/templates/teamlist.html
{% load i18n %}
{% block title %}
    {% trans "Cricket Team List" %}
{% endblock %}

<style>
table, td, th {  
  border: 1px solid #ddd;
  text-align: left;
}

table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 15px;
}
</style>
{% block content %}
<br>
<a href="{% url 'cricketapp:pointstable' %}">Points Table</a>
<br>
<a href="{% url 'cricketapp:matchdetails' %}">Match details</a>


    {% if allteam %}
        <table>
            <thead>
                <tr>
                    <th>{% trans "Team name" %}</th>
                    <th>{% trans "Team logo" %}</th>
                    <th>{% trans "other" %}</th>

                </tr>
            </thead>
            <tbody>
                {% for team in allteam %}
                    <tr>
                        <td><p>{{ team.name}}</p></td>
                        <td> <p><img src="{{ team.logouri }}" width="80px"></p> </td>
                        <td><a href="{% url 'cricketapp:teaminfo' team.id %}" target="_blank">
                        Team info</a></td>
                       
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>{% trans "No data found" %}</p>
    {% endif %}
{% endblock content %}